[package]
name = "test-proj"
description = "Helper to test whether project using opencv dependency compiles"
version = "0.1.0"
authors = ["Pro"]
edition = "2018"

[dependencies]
opencv = { path = "../.." }

[workspace]
